# Generated by Django 4.1.3 on 2022-11-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view',
            new_name='views',
        ),
    ]
